---
name: Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v4

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: 5.1

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install Lua test dependencies
        run: luarocks install busted

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color -q
          annotate: warning

      - name: Run Tests
        run: just test

      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -d -z -S

      - uses: actions/upload-artifact@v7
        with:
          name: Chomp-PR-${{ github.event.number }}
          path: .release/

      - name: Send Webhook Notification
        if: failure()
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        env:
          JOB_STATUS: ${{ job.status }}
          HOOK_OS_NAME: ${{ runner.os }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WORKFLOW_NAME: ${{ github.workflow }}
